#!/bin/bash

copy_files(){
	echo
}

check_programs(){
	if hash git 1>/dev/null 2>&1; then
		echo "Git installed."
	else
		echo "Git is not installed. Please install Git."
		exit 1
	fi
	
	if hash "$dotnet" 1>/dev/null 2>&1; then
		echo "Dotnet installed."
	else
		echo "Dotnet at \"$dotnet\" is not installed. Please check this scripts settings."
		exit 1
	fi
}

fetch_build_copy(){
	cd "$root"
	
	perform_build=true
	if [ ! -d "$sourcedir/.git" ]; then
		echo "Downloading $name."
		git clone -b "$branch" --recursive "$repourl" "$sourcedir" || exit 1
		cd "$sourcedir"
	else
		echo "Updating $name."
		cd "$sourcedir"
		old_hash=$(git rev-parse HEAD)
		if git pull -X theirs --recurse-submodules origin "$branch" && git checkout "$branch"; then
			new_hash=$(git rev-parse HEAD)
			
			[ "$old_hash" = "$new_hash" ] && perform_build=false
		else
			echo "Error while pulling changes, trying completely new clone."
			cd "$root"
			rm -rf "$sourcedir" 1>/dev/null 2>&1
			git clone -b "$branch" --recursive "$repourl" "$sourcedir" || exit 1
			cd "$sourcedir"
		fi
	fi
	
	if [ "$1" = "--build" ] || [ "$perform_build" = true ] || [ ! -d "$root/$builddir" ]; then
		echo -e "\nRestoring dependencies."
		$dotnet restore || exit 1
		
		copy_old_files=false
		if [ -d "$root/$builddir" ]; then
			copy_old_files=true
			echo -e "\nBacking up the current $name build."
			
			cd "$root"
			rm -rf "$oldbuilddir" 1>/dev/null 2>&1
			mv -fT "$builddir" "$oldbuilddir" 1>/dev/null 2>&1

			cd "$sourcedir"
		fi
		
		echo -e "\nBuilding new $name."
		$dotnet build --configuration Release -o "$root/$builddir" || { [ "$copy_old_files" = true ] && copy_files && exit 1 }
		
		cd "$root"
		
		# Copy files after building in case the build overwrote some files.
		[ "$copy_old_files" = true ] && copy_files
	else
		echo "Not performing build, nothing changed."
	fi
}

run_bot(){
	cd "$root/$rundir"
	$dotnet "$root/$builddir/$executable" || exit 1
}


force_build=false
config_file="build-run.cfg"

for var in "$@"; do
	case $1 in
		-h|--help)
			cat <<HELP
Usage: $(basename $0) [-h|-b] [configfile]

  -h, --help                    # Show this help.
  -b, --build                   # Force build on start.
      --create-sample-config    # Create a sample configuration file.
HELP
			exit 0
			;;
		-b|--build)
			force_build=true
			;;
		--create-sample-config)
			cat > build-run-sample.cfg <<SAMPLE_CONFIG
#!/bin/bash
# This is a sample configuration for the dotnet-build-run script.

# The name of your application. This is only used for echo messages.
name="Sample"
repourl="sample.git"
branch=master
# The dotnet-sdk executable which should be used to build and run the application.
dotnet=dotnet
# Root path of the script.
root="sample/root"
# Name of the repository directory in \$tempdir.
sourcedir="source"
# Name of the build directory.
builddir="build"
# Name of the directory where the previous build gets backed up before a new one is created.
oldbuilddir="\${builddir}_old"
# Name of the working directory for application runs.
rundir="run"
# Name of the executable in \$builddir.
executable="Sample.dll"

# If you need to copy files between two builds, do this here.
# When called, the working directory will be \$root
copy_files(){
	echo
}
SAMPLE_CONFIG
			exit 0
			;;
		*)
			config_file="$var"
			;;
	esac
done

. "$config_file"

if [ "$force_build" = true ] || [ ! -d "$root/$builddir" ]; then
	fetch_build_copy --build
fi

while :; do
	run_bot && fetch_build_copy || exit 1
done
